# payment_gateway_config null public null 0 0
# primaryColumns
#   payment_gateway_config_id
# foreignKeys
#   payment_gateway_config.payment_gateway_config_type_id ==> payment_gateway_config_type.payment_gateway_config_type_id
# checkConstraints---
title: "PaymentGatewayConfig"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "description"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "paymentGatewayConfigId"
  - "paymentGatewayConfigTypeId"
type: "object"
properties:
  paymentGatewayConfigId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "payment_gateway_config_id"
    exampleSetFlag: false
  paymentGatewayConfigTypeId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "payment_gateway_config_type_id"
    exampleSetFlag: false
  description:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "description"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
