# product_promo_product null public null 0 0
# primaryColumns
#   product_promo_id
#   product_promo_rule_id
#   product_promo_action_seq_id
#   product_promo_cond_seq_id
#   product_id
# foreignKeys
#   product_promo_product.product_id ==> product.product_id
#   product_promo_product.product_promo_appl_enum_id ==> enumeration.enum_id
#   product_promo_product.product_promo_id ==> product_promo.product_promo_id
# checkConstraints---
title: "ProductPromoProduct"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "productId"
  - "productPromoActionSeqId"
  - "productPromoApplEnumId"
  - "productPromoCondSeqId"
  - "productPromoId"
  - "productPromoRuleId"
type: "object"
properties:
  productPromoId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_promo_id"
    exampleSetFlag: false
  productPromoRuleId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_promo_rule_id"
    exampleSetFlag: false
  productPromoActionSeqId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_promo_action_seq_id"
    exampleSetFlag: false
  productPromoCondSeqId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_promo_cond_seq_id"
    exampleSetFlag: false
  productId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_id"
    exampleSetFlag: false
  productPromoApplEnumId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_promo_appl_enum_id"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
