# product_store_group_rollup null public null 0 0
# primaryColumns
#   product_store_group_id
#   parent_group_id
#   from_date
# foreignKeys
#   product_store_group_rollup.parent_group_id ==> product_store_group.product_store_group_id
#   product_store_group_rollup.product_store_group_id ==> product_store_group.product_store_group_id
# checkConstraints---
title: "ProductStoreGroupRollup"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "fromDate"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "parentGroupId"
  - "productStoreGroupId"
  - "sequenceNum"
  - "thruDate"
type: "object"
properties:
  productStoreGroupId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_store_group_id"
    exampleSetFlag: false
  parentGroupId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "parent_group_id"
    exampleSetFlag: false
  fromDate:
    type: "string"
    description: "from_date"
    format: "date-time"
    exampleSetFlag: false
  thruDate:
    type: "string"
    description: "thru_date"
    format: "date-time"
    exampleSetFlag: false
  sequenceNum:
    type: "number"
    description: "sequence_num"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
