# product_feature_category null public null 0 0
# primaryColumns
#   product_feature_category_id
# foreignKeys
#   product_feature_category.parent_category_id ==> product_feature_category.product_feature_category_id
# checkConstraints---
title: "ProductFeatureCategory"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "description"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "parentCategoryId"
  - "productFeatureCategoryId"
type: "object"
properties:
  productFeatureCategoryId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_feature_category_id"
    exampleSetFlag: false
  parentCategoryId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "parent_category_id"
    exampleSetFlag: false
  description:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "description"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
