# product_store_catalog null public null 0 0
# primaryColumns
#   product_store_id
#   prod_catalog_id
#   from_date
# foreignKeys
#   product_store_catalog.prod_catalog_id ==> prod_catalog.prod_catalog_id
#   product_store_catalog.product_store_id ==> product_store.product_store_id
# checkConstraints---
title: "ProductStoreCatalog"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "fromDate"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "prodCatalogId"
  - "productStoreId"
  - "sequenceNum"
  - "thruDate"
type: "object"
properties:
  productStoreId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_store_id"
    exampleSetFlag: false
  prodCatalogId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "prod_catalog_id"
    exampleSetFlag: false
  fromDate:
    type: "string"
    description: "from_date"
    format: "date-time"
    exampleSetFlag: false
  thruDate:
    type: "string"
    description: "thru_date"
    format: "date-time"
    exampleSetFlag: false
  sequenceNum:
    type: "number"
    description: "sequence_num"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
