# product_category_attribute null public null 0 0
# primaryColumns
#   product_category_id
#   attr_name
# foreignKeys
#   product_category_attribute.product_category_id ==> product_category.product_category_id
# checkConstraints---
title: "ProductCategoryAttribute"
required:
  - "attrDescription"
  - "attrName"
  - "attrValue"
  - "createdStamp"
  - "createdTxStamp"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "productCategoryId"
type: "object"
properties:
  productCategoryId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_category_id"
    exampleSetFlag: false
  attrName:
    maxLength: 60
    minLength: 0
    type: "string"
    description: "attr_name"
    exampleSetFlag: false
  attrValue:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "attr_value"
    exampleSetFlag: false
  attrDescription:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "attr_description"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
