# product_store_fin_act_setting null public null 0 0
# primaryColumns
#   product_store_id
#   fin_account_type_id
# foreignKeys
#   product_store_fin_act_setting.purchase_survey_id ==> survey.survey_id
#   product_store_fin_act_setting.product_store_id ==> product_store.product_store_id
#   product_store_fin_act_setting.replenish_method_enum_id ==> enumeration.enum_id
#   product_store_fin_act_setting.fin_account_type_id ==> fin_account_type.fin_account_type_id
# checkConstraints---
title: "ProductStoreFinActSetting"
required:
  - "accountCodeLength"
  - "accountValidDays"
  - "allowAuthToNegative"
  - "authValidDays"
  - "createdStamp"
  - "createdTxStamp"
  - "finAccountTypeId"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "minBalance"
  - "pinCodeLength"
  - "productStoreId"
  - "purchSurveyCopyMe"
  - "purchSurveySendTo"
  - "purchaseSurveyId"
  - "replenishMethodEnumId"
  - "replenishThreshold"
  - "requirePinCode"
  - "validateGCFinAcct"
type: "object"
properties:
  productStoreId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_store_id"
    exampleSetFlag: false
  finAccountTypeId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "fin_account_type_id"
    exampleSetFlag: false
  requirePinCode:
    maxLength: 1
    minLength: 0
    type: "string"
    description: "require_pin_code"
    exampleSetFlag: false
  validateGCFinAcct:
    maxLength: 1
    minLength: 0
    type: "string"
    description: "validate_g_c_fin_acct"
    exampleSetFlag: false
  accountCodeLength:
    type: "number"
    description: "account_code_length"
    exampleSetFlag: false
  pinCodeLength:
    type: "number"
    description: "pin_code_length"
    exampleSetFlag: false
  accountValidDays:
    type: "number"
    description: "account_valid_days"
    exampleSetFlag: false
  authValidDays:
    type: "number"
    description: "auth_valid_days"
    exampleSetFlag: false
  purchaseSurveyId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "purchase_survey_id"
    exampleSetFlag: false
  purchSurveySendTo:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "purch_survey_send_to"
    exampleSetFlag: false
  purchSurveyCopyMe:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "purch_survey_copy_me"
    exampleSetFlag: false
  allowAuthToNegative:
    maxLength: 1
    minLength: 0
    type: "string"
    description: "allow_auth_to_negative"
    exampleSetFlag: false
  minBalance:
    type: "number"
    description: "min_balance"
    exampleSetFlag: false
  replenishThreshold:
    type: "number"
    description: "replenish_threshold"
    exampleSetFlag: false
  replenishMethodEnumId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "replenish_method_enum_id"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
