# product_category null public null 0 0
# primaryColumns
#   product_category_id
# foreignKeys
#   product_category.primary_parent_category_id ==> product_category.product_category_id
#   product_category.product_category_type_id ==> product_category_type.product_category_type_id
# checkConstraints---
title: "ProductCategory"
required:
  - "categoryImageUrl"
  - "categoryName"
  - "createdStamp"
  - "createdTxStamp"
  - "description"
  - "detailScreen"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "linkOneImageUrl"
  - "linkTwoImageUrl"
  - "longDescription"
  - "primaryParentCategoryId"
  - "productCategoryId"
  - "productCategoryTypeId"
  - "showInSelect"
type: "object"
properties:
  productCategoryId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_category_id"
    exampleSetFlag: false
  productCategoryTypeId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_category_type_id"
    exampleSetFlag: false
  primaryParentCategoryId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "primary_parent_category_id"
    exampleSetFlag: false
  categoryName:
    maxLength: 100
    minLength: 0
    type: "string"
    description: "category_name"
    exampleSetFlag: false
  description:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "description"
    exampleSetFlag: false
  longDescription:
    maxLength: 2147483647
    minLength: 0
    type: "string"
    description: "long_description"
    exampleSetFlag: false
  categoryImageUrl:
    maxLength: 2000
    minLength: 0
    type: "string"
    description: "category_image_url"
    exampleSetFlag: false
  linkOneImageUrl:
    maxLength: 2000
    minLength: 0
    type: "string"
    description: "link_one_image_url"
    exampleSetFlag: false
  linkTwoImageUrl:
    maxLength: 2000
    minLength: 0
    type: "string"
    description: "link_two_image_url"
    exampleSetFlag: false
  detailScreen:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "detail_screen"
    exampleSetFlag: false
  showInSelect:
    maxLength: 1
    minLength: 0
    type: "string"
    description: "show_in_select"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
