# product_geo null public null 0 0
# primaryColumns
#   product_id
#   geo_id
# foreignKeys
#   product_geo.product_geo_enum_id ==> enumeration.enum_id
#   product_geo.product_id ==> product.product_id
#   product_geo.geo_id ==> geo.geo_id
# checkConstraints---
title: "ProductGeo"
required:
  - "createdStamp"
  - "createdTxStamp"
  - "description"
  - "geoId"
  - "lastUpdatedStamp"
  - "lastUpdatedTxStamp"
  - "productGeoEnumId"
  - "productId"
type: "object"
properties:
  productId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_id"
    exampleSetFlag: false
  geoId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "geo_id"
    exampleSetFlag: false
  productGeoEnumId:
    maxLength: 20
    minLength: 0
    type: "string"
    description: "product_geo_enum_id"
    exampleSetFlag: false
  description:
    maxLength: 255
    minLength: 0
    type: "string"
    description: "description"
    exampleSetFlag: false
  lastUpdatedStamp:
    type: "string"
    description: "last_updated_stamp"
    format: "date-time"
    exampleSetFlag: false
  lastUpdatedTxStamp:
    type: "string"
    description: "last_updated_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdStamp:
    type: "string"
    description: "created_stamp"
    format: "date-time"
    exampleSetFlag: false
  createdTxStamp:
    type: "string"
    description: "created_tx_stamp"
    format: "date-time"
    exampleSetFlag: false
exampleSetFlag: false
